swagger: "2.0"
info:
  description: Basic example of putting together an OpenAPI spec (Swagger v2 format).
  version: "1"
  title: "Demo OpenAPI Spec"
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: users
    description: Interfaces for Users
  - name: orders
    description: Interfaces for Users Orders
  - name: widgets
    description: Interfaces for Widgets
host: localhost:4200
basePath: /api/v1
schemes:
  - https
  - http
paths:
  /users:
    post:
      tags:
        - users
      operationId: add-user
      summary: Add a new User
      parameters:
        - name: user
          in: body
          required: true
          description: New User Data
          schema:
            $ref: '#/definitions/user'
      responses:
        '204':
          description: User created.
        '400':
          description: Invalid data.
        '500':
          description: Server Error.
    get:
      tags:
        - users
      operationId: get-users
      summary: List of all Users
      responses:
        '200':
          description: Returns a JSON Array of User Objects
          schema:
            $ref: "#/definitions/userList"
    put:
      tags:
        - users
      operationId: put-users
      summary: Modify all Users
      responses:
        '400':
          description: Feature not enabled
    delete:
      tags:
        - users
      operationId: delete-users
      summary: Delete all Users
      responses:
        '400':
          description: Feature not enabled
  /users/{userID}:
    get:
      tags:
        - users
      operationId: get-user
      summary: Get a Specific User by ID
      parameters:
        - name: userID
          in: path
          description: User Specific ID
          required: true
          type: integer
      responses:
        '200':
          description: Returns a User Object
          schema:
            $ref: "#/definitions/user"
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
    put:
      tags:
        - users
      operationId: put-user
      summary: Update a Specific User by ID
      parameters:
        - name: userID
          in: path
          description: User Specific ID
          required: true
          type: integer
        - name: user
          in: body
          required: true
          description: New User Data
          schema:
            $ref: '#/definitions/user'
      responses:
        '204':
          description: User Modified.
        '400':
          description: Invalid data.
        '500':
          description: Server Error.
    delete:
      tags:
        - users
      operationId: delete-user
      summary: Delete a Specific User by ID
      parameters:
        - name: userID
          in: path
          description: User Specific ID
          required: true
          type: integer
      responses:
        '204':
          description: User Deleted.
  /widgets:
    post:
      tags:
        - widgets
      operationId: add-widget
      summary: Add a new widget
      parameters:
        - name: widget
          in: body
          required: true
          description: New Widget Data
          schema:
            $ref: '#/definitions/widget'
      responses:
        '204':
          description: Widget created.
        '400':
          description: Invalid data.
        '500':
          description: Server Error.
    get:
      tags:
        - widgets
      operationId: get-widgets
      summary: List of all widgets
      responses:
        '200':
          description: Returns a JSON Array of Widget Objects
          schema:
            $ref: "#/definitions/widgetList"
    put:
      tags:
        - widgets
      operationId: put-widgets
      summary: Modify all Widget
      responses:
        '400':
          description: Feature not enabled
    delete:
      tags:
        - widgets
      operationId: delete-widgets
      summary: Delete all widgets
      responses:
        '400':
          description: Feature not enabled
  /widgets/{widgetID}:
    get:
      tags:
        - widgets
      operationId: get-widget
      summary: Get a Specific Widget by ID
      parameters:
        - name: widgetID
          in: path
          description: Widget Specific ID
          required: true
          type: integer
      responses:
        '200':
          description: Returns a Widget Object
          schema:
            $ref: "#/definitions/widget"
        '400':
          description: Invalid ID supplied
        '404':
          description: Widget not found
    put:
      tags:
        - widgets
      operationId: put-widget
      summary: Update a Specific Widget by ID
      parameters:
        - name: widgetID
          in: path
          description: Widget Specific ID
          required: true
          type: integer
        - name: widget
          in: body
          required: true
          description: New Widget Data
          schema:
            $ref: '#/definitions/widget'
      responses:
        '204':
          description: Widget Modified.
        '400':
          description: Invalid data.
        '500':
          description: Server Error.
    delete:
      tags:
        - widgets
      operationId: delete-widget
      summary: Delete a Specific Widget by ID
      parameters:
        - name: widgetID
          in: path
          description: Widget Specific ID
          required: true
          type: integer
      responses:
        '204':
          description: Widget Deleted.
  /orders:
    post:
      tags:
        - orders
      operationId: add-order
      summary: Add a new order
      parameters:
        - name: order
          in: body
          required: true
          description: New Order Data
          schema:
            $ref: '#/definitions/order'
      responses:
        '204':
          description: Order created.
        '400':
          description: Invalid data.
        '500':
          description: Server Error.
    get:
      tags:
        - orders
      operationId: get-orders
      summary: List of all orders
      responses:
        '200':
          description: Returns a JSON Array of Order Objects
          schema:
            $ref: "#/definitions/orderList"
    put:
      tags:
        - orders
      operationId: put-orders
      summary: Modify all Orders
      responses:
        '400':
          description: Feature not enabled
    delete:
      tags:
        - orders
      operationId: delete-orders
      summary: Delete all Orders
      responses:
        '400':
          description: Feature not enabled
  /orders/{orderID}:
    get:
      tags:
        - orders
      operationId: get-order
      summary: Get a Specific Order by ID
      parameters:
        - name: widgetID
          in: path
          description: Order Specific ID
          required: true
          type: integer
      responses:
        '200':
          description: Returns a Order Object
          schema:
            $ref: "#/definitions/widget"
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
    put:
      tags:
        - orders
      operationId: put-order
      summary: Update a Specific Order by ID
      parameters:
        - name: orderID
          in: path
          description: Order Specific ID
          required: true
          type: integer
        - name: order
          in: body
          required: true
          description: New Order Data
          schema:
            $ref: '#/definitions/order'
      responses:
        '204':
          description: Order Modified.
        '400':
          description: Invalid data.
        '500':
          description: Server Error.
    delete:
      tags:
        - orders
      operationId: delete-order
      summary: Delete a Specific Order by ID
      parameters:
        - name: orderID
          in: path
          description: Order Specific ID
          required: true
          type: integer
      responses:
        '204':
          description: Order Deleted.


definitions:
  user:
    type: object
    properties:
      id:
        type: integer
        description: User ID
      username:
        type: string
        description: User Name
      password:
        type: string
        description: User Password
      apikey:
        type: string
        format: uuid
        description: A user specific API Key
      isadmin:
        type: boolean
        description: Is the user an Admin
  userList:
    type: object
    properties:
      total:
        type: integer
      users:
        type: array
        items:
          $ref: "#/definitions/user"
        description: Array of Widgets
  widget:
    type: object
    properties:
      id:
        type: integer
        description: Widget ID
      name:
        type: string
        description: Widget Name
      price:
        type: number
        format: double
        description: Widget Price
  widgetList:
    type: object
    properties:
      total:
        type: integer
      widgets:
        type: array
        items:
          $ref: "#/definitions/widget"
  order:
    type: object
    properties:
      id:
        type: integer
        description: Order ID
      user:
        type: integer
        description: User ID
      widgets:
        type: array
        items:
          type: object
          properties:
            widgetid:
              type: integer
              description: The Widget ID for this order item
            quantity:
              type: integer
              minimum: 1
              description: How many of the widget are in the order
        description: Array of Widgets
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://example.com/oauth/authorize
    tokenUrl: https://example.com/oauth/token
    scopes:
      view_users: view users
      admin_users: admin all users
      view_widgets: view widgets
      admin_widgets: admin widgets
      view_orders: view orders
      admin_orders: admin orders
